[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "bold"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "italic"

[font.normal]
family = "RobotoMonoNerdFontMono"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control"

[window]
opacity = 0.9

[window.padding]
x = 6
y = 6

